name: Release

on:
  push:
    tags:
      - v*

jobs:

  release:

    name: Release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    container:
      image: emscripten/emsdk

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: make container-build

      - name: Publish
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const tag = context.ref.replace('refs/tags/', '');
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
            });
            const asset = await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              name: 'animate_images.user.js',
              data: await fs.readFileSync("build/animate_images.user.js"),
              label: 'User script (js)',
            });
